module.exports = [
  {
    id: "1",
    title: "Book1",
    author: "Author1",
    classic: false,
    year: 1900,
  },
  {
    id: "2",
    title: "Book2",
    author: "Author2",
    classic: true,
    year: 1910,
  },
  {
    id: "3",
    title: "Book3",
    author: "Author3",
    classic: false,
    year: 1990,
  },
  {
    id: "4",
    title: "Book4",
    author: "Author4",
    classic: true,
    year: 1950,
  },
  {
    id: "5",
    title: "Book5",
    author: "Author5",
    classic: false,
    year: 1940,
  },
  {
    id: "6",
    title: "Book6",
    author: "Author6",
    classic: true,
    year: 1980,
  },
  {
    id: "7",
    title: "Book7",
    author: "Author7",
    classic: false,
    year: 1950,
  },
  {
    id: "8",
    title: "Book8",
    author: "Author8",
    classic: true,
    year: 1930,
  },
];
